### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/ConAlerts#1]
Please follow setup protocol for a new site for con-alerts.com at GoDaddy. Please copy the site from conservativecontacts.com.

u/n: brettafarley
p/w: 4forjesus

**Comment by supportast** [comment]
Done

**Comment by brettfarley** [comment]
Thanks. What’s the login?

On March 15, 2016 at 3:42:17 AM, supportast (notifications@github.com) wrote:

Done

**Comment by supportast** [comment]
u/n: brettafarley
p/w: 4forjesus
