### ISSUE TITLE
Upload new logo

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/ConAlerts#2]
![1](https://cloud.githubusercontent.com/assets/13319038/13682438/6520e414-e6c7-11e5-8d82-b559e0ddfac5.jpg)

**Comment by supportast** [comment]
Done

**Comment by brettfarley** [comment]
Please replace current logo on site with this logo.
![4](https://cloud.githubusercontent.com/assets/13319038/13801920/b8a7e7a4-eb04-11e5-8e86-0f1bf4d879e6.png)

**Comment by supportast** [comment]
Done . Please Check.
