### ISSUE TITLE
Various tweaks

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/ConAlerts#3]
Please delete social icons in the menu bar. Change subscribe to bar in header to "Subscribe to Conservative Alerts". Please change menu bar, hover over and slider light box colors to red.

**Comment by supportast** [comment]
Done

**Comment by brettfarley** [comment]
The menu, subscribe, hover, and lightbox color are all still blue. Should be red. See screenshot.
![screen shot 2016-03-15 at 11 19 49 pm](https://cloud.githubusercontent.com/assets/13319038/13801899/80f065ca-eb04-11e5-82db-f845e93174a5.jpg)

**Comment by supportast** [comment]
Done

**Comment by supportast** [comment]
Hi Brett,

This issues I have already done last night. I think someone else replace the css file.

Please check now I have done the task again.

Thanks

**Comment by supportast** [comment]
Done . Please check. And this task was done yesterday also . I think someone else was also working on the same . due to this got reverted .

**Comment by brettfarley** [comment]
That's weird because you and I were the only two working on it. Thanks!
