### ISSUE TITLE
Urgent: Reformat Post template

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/ConAlerts#4]
Please reformat post template so that posts so that there is space for a horizontal ad, an image below that, body text below that and tall "skyscraper" ads on both side margins.

Also, just below the image I need a Facebook like button installed as a default using the following code snippet. 

Here's an example of how Posts should be laid out: http://www.youngcons.com/cnn-polls-viewers-trumps-convention-speech-they-loved-it/

<iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FConservative-Alerts-188392531552685&width=100&layout=button&action=like&size=large&show_faces=false&share=true&height=65&appId=279519543652" width="100" height="65" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

**Comment by brettfarley** [comment]
Let's plug in the attached ad codes for the 728 and 300 spots as soon as you can.
[Conservative Alerts - 300x250 - RevenueStripe.txt](https://github.com/VeritasStrategies/ConAlerts/files/400785/Conservative.Alerts.-.300x250.-.RevenueStripe.txt)
[Conservative Alerts - 728x90 - RevenueStripe.txt](https://github.com/VeritasStrategies/ConAlerts/files/400786/Conservative.Alerts.-.728x90.-.RevenueStripe.txt)

**Comment by brettfarley** [comment]
Modifications:
1. Increase the width of the main content area by 30%
2. Delete the title "Blog post" at the top of the page and move everything up so that the top ad is just blew the menu bar.
3. Delete the date that appear next the share button
4. I want the 'like' button to look like the one attached
5. Delete the 'share' button that appears next to the 'like' button
6. Fix the two 300x250 ads on the margins. They are on top of each other instead of stacked. See screenshot.
   ![screen shot 2016-08-08 at 4 19 39 pm](https://cloud.githubusercontent.com/assets/13319038/17496734/304d2b60-5d84-11e6-998f-6563f521492c.jpg)
   ![screen shot 2016-08-08 at 4 21 03 pm](https://cloud.githubusercontent.com/assets/13319038/17496737/34437be8-5d84-11e6-87e1-4221f6cbeb1d.jpg)

**Comment by supportast** [comment]
1 Increase the width of the main content area by 30% - done
2. Delete the title "Blog post" at the top of the page and move everything up so that the top ad is just blew the menu bar. - Done
3. Delete the date that appear next the share button - Done 
4. I want the 'like' button to look like the one attached - I have done but not reflecting ..cache issue ...I  seems that issue is our CSS gets loaded first and this button comes from FB . I will try to find another solution  for this .
5. Delete the 'share' button that appears next to the 'like' button - Same issue as point no 4 
6. Fix the two 300x250 ads on the margins. They are on top of each other instead of stacked. See  - Pending

**Comment by supportast** [comment]
Fix the two 300x250 ads on the margins. They are on top of each other instead of stacked. See  - please explain this point more

**Comment by brettfarley** [comment]
I want it designed just like the mockup I sent (see attached) except I want the 300x250 units on top of each other in the place where you see "skyscraper ad space".
![screen shot 2016-07-26 at 11 37 10 am](https://cloud.githubusercontent.com/assets/13319038/17517284/5d1588ca-5e08-11e6-89b3-17082c2a957f.jpg)

**Comment by supportast** [comment]
Please check page is done for the desktop version .  For responsive I need to work on that.  I am not available on  Monday as its a national holiday ..

Thanks

**Comment by brettfarley** [comment]
1. The ads in the left margin should also appear in the right margin as well. They should also be closer to together.
2. Is it possible not reduce the size of the logo for the Post template, maybe to 25% of its current size?
3. The ad at the bottom of the page is still WAY too far down. It should be as close to the bottom of the Post text as the top ad is to the headline.

**Comment by supportast** [comment]
The ads in the left margin should also appear in the right margin as well. They should also be closer to together. - Done Please check 

Is it  possible not reduce the size of the logo for the Post template, maybe to 25% of its current size? - Done its now 25 % 

The ad at the bottom of the page is still WAY too far down. It should be as close to the bottom of the Post text as the top ad is to the headline. - I have reduced the gap..please check and let me know if has to be above the form .

**Comment by brettfarley** [comment]
This is still wrong. There should be ads on the right hand margin (see the mockup above). This is still missing. See attached screenshot.
![screen shot 2016-08-16 at 8 55 11 am](https://cloud.githubusercontent.com/assets/13319038/17701373/3e109d98-638f-11e6-98f3-2538e0773981.jpg)

**Comment by supportast** [comment]
This the screenshot at me end . I am checking it may be issue with different screen resolution . 

![image](https://cloud.githubusercontent.com/assets/17302014/17724353/0868e0e4-645f-11e6-87fa-a8c341bd5dd6.png)

**Comment by supportast** [comment]
1. for the Logo I was little confused with test so I have made it 75% that is reduced by 25% .. Please confirm it it requires to be 25% and reduced by 75%.
2. Layout setup done for resolutions above 1024 width . For below this width ..we need to follow a different layout as ads have fixed width .  Please suggest .

**Comment by brettfarley** [comment]
This is how it looks on Safari. This is still not done correctly. We're spending way too much time and money on this. I shouldn't be that difficult.
![screen shot 2016-08-17 at 9 09 33 am](https://cloud.githubusercontent.com/assets/13319038/17739337/64db6aea-645a-11e6-995e-cce849328cb4.jpg)

**Comment by supportast** [comment]
Hi,
Please check the screen shot at me end from safari ..its showing correct .  I tested on safari also before updating to you. can you please share with the link for the page  and the screen resolution . I  know you have asked me to stop work but its my responsibility to complete work which I was doing .. I  will not bill for this also. just ..please let me know the above details as I don't want to leave the work undone.

http://www.con-alerts.com/obama-calls-in-techies-for-the-fix/

![screen shot 2016-08-18 at 10 56 30 am](https://cloud.githubusercontent.com/assets/17302014/17763023/47aa7ba8-6533-11e6-9a55-dc755d883a71.png)

**Comment by brettfarley** [comment]
Thanks for agreeing to finish this task. The ads are still not lining up properly in Safari. See attached screenshot. Let's delete the ads on the right and left hand columns so that only the ads at top and bottom are appearing. We can fix it later.

![screen shot 2016-08-18 at 10 22 57 am](https://cloud.githubusercontent.com/assets/13319038/17779625/e565e5ae-652d-11e6-8ed4-e525559752e3.jpg)

**Comment by supportast** [comment]
Hi ,
I found the issue and corrected for the ipad resolution . please check .
But this work has to be done for iphone and other android resolutions . which will take  around 2 hrs to do and same time will be required if you want to remove the ads because I will have to modify the page container width and adjust the post accordingly . 

So please suggest what way you want it to do . 

Thanks
